training/src/main/java/com/revature/caliber/training/beans/Trainee.java, training/src/main/java/com/revature/caliber/training/data/Facade.java, training/src/main/java/com/revature/caliber/training/data/TraineeDAO.java, training/src/main/java/com/revature/caliber/training/data/implementations/TraineeDAOImplementation.java, training/src/main/java/com/revature/caliber/training/service/BusinessDelegate.java, training/src/main/java/com/revature/caliber/training/service/TraineeService.java, training/src/main/java/com/revature/caliber/training/web/controllers/TraineeController.java, training/src/main/webapp/WEB-INF/beans.xml, training/src/test/java/com/revature/caliber/data/implementations/TraineeDAOImplementationTest.java
Fixed what I had to do for controller,
Added comments,
Added logger
=> Fixes for trainee part of the api

assessments/src/main/java/com/revature/caliber/assessments/beans/Grade.java, assessments/src/main/java/com/revature/caliber/assessments/data/Facade.java, assessments/src/main/java/com/revature/caliber/assessments/data/GradeDAO.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/FacadeImplementation.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/GradeDAOImpl.java, assessments/src/test/java/com/revature/caliber/initial/GradeTest.java, training/src/main/java/com/revature/caliber/training/service/Implementations/.gitignore, training/src/main/java/com/revature/caliber/training/service/Implementations/BusinessDelegateImplementation.java
Also fixed some code smell issues
=> Added Grade methods to Facade and Implementation

caliber/src/main/java/com/revature/caliber/controllers/TrainerBatchController.java, caliber/src/test/java/com/revature/caliber/controllers/trainer/TrainerBatchControllerTest.java
Controller for obtaining trainer batches was created
Only Get method types were created so far.
Controller does not use middle tier since middle tier is still under controller
Mock data was used and will be removed after middle tier connection
Unit tests will change after connecting controller to middle tier
Unit tests rely on mock data
----- previous pull request for this branch was closed due to edits -----
=> Caliber trainer batch controller

caliber/src/main/java/com/revature/caliber/controllers/QCBatchController.java, caliber/src/test/java/com/revature/caliber/controllers/qc/QCBatchControllerTest.java
Similar construction to the previously composed trainer batch constructor
=> Started creating the qc batch controller

caliber/src/main/java/com/revature/caliber/controllers/QCBatchController.java
Changes in response to code smell form SonarQube
=> Caliber qc batch controller

caliber/src/main/java/com/revature/caliber/controllers/VPBatchController.java, caliber/src/test/java/com/revature/caliber/controllers/vp/VPBatchControllerTest.java
Created and tested endpoints(GET) for vp batch controller
=> Caliber vp batch controller

caliber/src/main/webapp/app/resources/js/config/modules.js, caliber/src/main/webapp/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/app/resources/js/controllers/trainerHomeController.js, caliber/src/main/webapp/app/resources/js/factories/lineChartFactory.js, caliber/src/main/webapp/index.html
- Created a function in line chart factory that returns a line chart that displays a trainee's progress.
- Test data was sent from trainee landing page controller
=> Line chart factory

caliber/pom.xml, caliber/src/main/java/com/revature/caliber/beans/Batch.java, caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/controllers/QCBatchController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainerBatchController.java, caliber/src/main/java/com/revature/caliber/middleTier/BusinessDelegate.java, caliber/src/main/webapp/WEB-INF/beans.xml, caliber/src/main/webapp/WEB-INF/web.xml, caliber/src/main/webapp/app/partials/home/qc-home.html, caliber/src/main/webapp/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/app/resources/js/controllers/qcHomeController.js, caliber/src/main/webapp/app/resources/js/controllers/trainerHomeController.js, caliber/src/main/webapp/app/resources/js/controllers/vpHomeController.js, caliber/src/main/webapp/app/resources/js/factories/delegateFactory.js, caliber/src/main/webapp/app/resources/js/factories/lineChartFactory.js, caliber/src/main/webapp/app/resources/js/factories/pieChartFactory.js, caliber/src/main/webapp/app/resources/js/factories/qcFactory.js, caliber/src/main/webapp/app/resources/js/factories/trainerFactory.js, caliber/src/main/webapp/app/resources/js/factories/vpFactory.js, caliber/src/main/webapp/pages/index.html, caliber/src/test/java/com/revature/caliber/controllers/qc/QCBatchControllerTest.java, caliber/src/test/java/com/revature/caliber/controllers/trainer/TrainerBatchControllerTest.java
Changed mappings folder, using delegate in controller, and changed tests.
=> FakeDataGeneratedInBusinessDelegateConstructorBranch

training/src/main/java/com/revature/caliber/training/data/BatchDAO.java, training/src/main/java/com/revature/caliber/training/service/BatchService.java, training/src/main/java/com/revature/caliber/training/web/controllers/BatchController.java, training/src/test/java/com/revature/caliber/controller/implementations/BatchControllerImplementationTest.java, training/src/test/java/com/revature/caliber/web/controller/implementations/BatchControllerImplementationTest.java
Test package for controller classes and methods in Training project
=> Created package for testing controller

caliber/src/test/java/com/revature/caliber/controllers/vp/VPBatchControllerTest.java
=> Changed before to before class

salesforce/src/main/java/com/revature/caliber/salesforce/controllers/PreAuthentication.java, salesforce/src/main/webapp/WEB-INF/beans.xml
Removed finally block which was causing issues in sonarqube
=> Salesforce

training/src/main/java/com/revature/caliber/training/beans/Trainer.java, training/src/main/java/com/revature/caliber/training/data/Facade.java, training/src/main/java/com/revature/caliber/training/data/TrainerDAO.java, training/src/main/java/com/revature/caliber/training/data/implementations/FacadeImplementation.java, training/src/main/java/com/revature/caliber/training/data/implementations/TrainerDAOImplementation.java, training/src/main/java/com/revature/caliber/training/service/BusinessDelegate.java, training/src/main/java/com/revature/caliber/training/service/TrainerService.java, training/src/main/java/com/revature/caliber/training/service/implementations/BusinessDelegateImplementation.java, training/src/main/java/com/revature/caliber/training/service/implementations/TrainerServiceImplementation.java, training/src/main/java/com/revature/caliber/training/web/controllers/TrainerController.java, training/src/test/java/com/revature/caliber/data/implementations/TrainerDAOImplementationTest.java
Trainer method getByEmail added, getByName removed, and deleteTrainer removed.
=> Sherlockapi

assessments/src/main/java/com/revature/caliber/assessments/data/implementations/FacadeImplementation.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/QCStatusDAOImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/BusinessDelegate.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BusinessDelegateImpl.java
=> fixed errors

caliber/src/main/webapp/app/resources/js/controllers/trainerHomeController.js
Changed names for holding returning chart and line objects.
=> Trainer Controller Edit

caliber/src/main/java/com/revature/caliber/gateway/ApiGateway.java, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/TrainingService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java, caliber/src/main/webapp/WEB-INF/beans.xml
Finished crud calls to training module - trainee service.
(ApiGateway and TrainingService interfaces/classes)
=> Traineegateway

training/src/main/java/com/revature/caliber/training/data/TrainerDAO.java, training/src/main/java/com/revature/caliber/training/data/implementations/TrainerDAOImplementation.java, training/src/test/java/com/revature/caliber/data/implementations/TrainerDAOImplementationTest.java
after and before annotations added to junit testing of trainerdao for better testing.
=> better testing practice

assessments/src/test/java/com/revature/caliber/assessments/data/implementations/QCNoteDAOImplementationTest.java
A very fast and important fix.
=> Qcnote quickfix

assessments/src/main/java/com/revature/caliber/assessments/beans/TrainerNote.java, assessments/src/main/java/com/revature/caliber/assessments/data/TrainerNoteDAO.java, assessments/src/main/java/com/revature/caliber/assessments/service/TrainerNoteService.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/TrainerNoteServiceImpl.java, assessments/src/main/java/com/revature/caliber/assessments/web/controllers/TrainerNoteController.java
=> Trainer note cleanup

assessments/src/main/java/com/revature/caliber/assessments/service/BusinessDelegate.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BusinessDelegateImpl.java, assessments/src/test/java/com/revature/caliber/assessments/data/implementations/TrainerNoteDAOImplTest.java
=> Oreo assigned feature

caliber/src/main/java/com/revature/caliber/gateway/services/TrainingService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java, caliber/src/main/webapp/WEB-INF/beans.xml, caliber/src/test/java/com/revature/caliber/gateway/Training/BatchGatewayTest.java, training/src/main/java/com/revature/caliber/training/web/controllers/BatchController.java
=> Batch service caliber

assessments/src/main/java/com/revature/caliber/assessments/beans/Note.java, assessments/src/main/java/com/revature/caliber/assessments/beans/QCNote.java, assessments/src/main/java/com/revature/caliber/assessments/data/Facade.java, assessments/src/main/java/com/revature/caliber/assessments/data/QCNoteDAO.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/FacadeImplementation.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/QCNoteDAOImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/BusinessDelegate.java, assessments/src/main/java/com/revature/caliber/assessments/service/QCNoteService.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BusinessDelegateImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/NoteServiceImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/QCNoteServiceImplementation.java, assessments/src/main/java/com/revature/caliber/assessments/web/controllers/QCNoteController.java, assessments/src/test/java/com/revature/caliber/assessments/data/implementations/QCNoteDAOImplementationTest.java, caliber/src/main/java/com/revature/caliber/beans/exceptions/TrainingServiceTraineeOperationException.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java
Fixed the "bug" and other things
=> Sonarq fix ilya

assessments/src/main/java/com/revature/caliber/assessments/data/Facade.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/FacadeImplementation.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/QCStatusDAOImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/BusinessDelegate.java, assessments/src/main/java/com/revature/caliber/assessments/service/QCStatusService.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BusinessDelegateImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/QCStatusServiceImpl.java, assessments/src/main/java/com/revature/caliber/assessments/web/controllers/QCStatusController.java
sam and bryan is working on failed build
=> QCStatus Controller added

assessments/src/main/java/com/revature/caliber/assessments/data/implementations/QCNoteDAOImpl.java, assessments/src/main/java/com/revature/caliber/assessments/data/implementations/TrainerNoteDAOImpl.java
fixed query did not return a unique result: 2 
by adding setMaxResults(1) to uniqueResult()
=> Fixed 2 related build errors

assessments/src/main/java/com/revature/caliber/assessments/beans/Category.java, training/src/main/java/com/revature/caliber/training/beans/Week.java, training/src/main/java/com/revature/caliber/training/web/controllers/WeekController.java
No more recursion problem with week bean and fixed duplicate json results
=> Fixed Week Controllers

caliber/src/main/java/com/revature/caliber/gateway/ApiGateway.java, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/TrainingService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java, caliber/src/main/webapp/WEB-INF/beans.xml
Provided changes for training->trainee
=> Trainee get by name -> by email in caliber project

assessments/assessments-ddl.sql, assessments/src/main/java/com/revature/caliber/assessments/beans/Assessment.java, assessments/src/main/java/com/revature/caliber/assessments/beans/Category.java, assessments/src/main/java/com/revature/caliber/assessments/beans/Grade.java, assessments/src/main/java/com/revature/caliber/assessments/beans/QCStatus.java, training/src/main/java/com/revature/caliber/training/beans/Trainee.java, training/src/main/java/com/revature/caliber/training/beans/Week.java
created statements for CALIBER_CATEGORY_WEEKS to map ElementCollection
=> Added to sql script

training/src/test/java/com/revature/caliber/data/implementations/TraineeDAOImplementationTest.java
One-liner fix (forgot to do it)
=> Little fix

assessments/src/main/java/com/revature/caliber/assessments/web/controllers/GradeController.java
=> Finished grade controller methods

caliber/src/main/java/com/revature/caliber/beans/exceptions/AssessmentServiceAssessmentOperationException.java, caliber/src/main/java/com/revature/caliber/beans/exceptions/AssessmentServiceOperationException.java, caliber/src/main/java/com/revature/caliber/beans/exceptions/TrainingServiceTraineeOperationException.java, caliber/src/main/java/com/revature/caliber/controllers/AllController.java, caliber/src/main/java/com/revature/caliber/controllers/QCBatchController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainerBatchController.java, caliber/src/main/java/com/revature/caliber/controllers/VPBatchController.java, caliber/src/main/java/com/revature/caliber/gateway/ApiGateway.java, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/TrainingService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/AssessmentServiceImpl.java
Added new controllers and fixed some problems
=> Added new controllers and fixed some problems

assessments/src/main/java/com/revature/caliber/assessments/web/controllers/TrainerNoteController.java, caliber/src/main/java/com/revature/caliber/gateway/ApiGateway.java, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/AssessmentService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/AssessmentServiceImpl.java, caliber/src/main/webapp/WEB-INF/beans.xml
AssessmentServiceImpl and ApiGateway
=> Healthy tier

assessments/src/main/java/com/revature/caliber/assessments/service/implementations/AssessmentServiceImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BatchNoteServiceImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/BusinessDelegateImpl.java, assessments/src/main/java/com/revature/caliber/assessments/service/implementations/CategoryServiceImpl.java, caliber/src/main/java/com/revature/caliber/assessment/beans/Assessment.java, caliber/src/main/java/com/revature/caliber/assessment/beans/BatchNote.java, caliber/src/main/java/com/revature/caliber/assessment/beans/Category.java, caliber/src/main/java/com/revature/caliber/assessment/beans/Grade.java, caliber/src/main/java/com/revature/caliber/assessment/beans/Note.java, caliber/src/main/java/com/revature/caliber/assessment/beans/QCNote.java, caliber/src/main/java/com/revature/caliber/assessment/beans/QCStatus.java, caliber/src/main/java/com/revature/caliber/assessment/beans/TrainerNote.java, caliber/src/test/java/com/revature/caliber/controllers/AllControllerTest.java
Added some tests for the controllers
=> Added some tests for the controllers

assessments/src/test/java/com/revature/caliber/assessments/data/implementations/BatchNoteDAOImplTest.java, assessments/src/test/java/com/revature/caliber/assessments/data/implementations/QCNoteDAOImplementationTest.java, assessments/src/test/java/com/revature/caliber/assessments/data/implementations/QCStatusDAOImplTest.java, assessments/src/test/java/com/revature/caliber/assessments/data/implementations/TrainerNoteDAOImplTest.java, assessments/src/test/java/com/revature/caliber/assessments/service/implementations/AssessmentServiceTest.java, assessments/src/test/java/com/revature/caliber/assessments/service/implementations/CategoryServiceImplTest.java, assessments/src/test/java/com/revature/caliber/initial/GradeTest.java, caliber/src/test/java/com/revature/caliber/gateway/impl/ApiGatewayImplTest.java, caliber/src/test/java/com/revature/caliber/gateway/services/impl/AssessmentServiceImplTest.java, caliber/src/test/java/com/revature/caliber/gateway/services/impl/TrainingServiceImplTest.java, caliber/src/test/java/com/revature/caliber/gateway/training/BatchGatewayTest.java, caliber/src/test/java/com/revature/caliber/initial/ApiGatewayTest.java, caliber/src/test/java/com/revature/caliber/initial/AssessmentServiceImplTest.java, caliber/src/test/java/com/revature/caliber/initial/ControllerTests.java, training/src/test/java/com/revature/caliber/data/implementations/BatchDAOImplementationTest.java, training/src/test/java/com/revature/caliber/data/implementations/CategoryDAOImplTest.java, training/src/test/java/com/revature/caliber/data/implementations/TierDAOImplementationTest.java, training/src/test/java/com/revature/caliber/data/implementations/TraineeDAOImplementationTest.java, training/src/test/java/com/revature/caliber/data/implementations/TrainerDAOImplementationTest.java, training/src/test/java/com/revature/caliber/data/implementations/WeekDAOImplementationTest.java, training/src/test/java/com/revature/caliber/web/controller/implementations/TrainerControllerImplementationTest.java
Added
@After
public void close() {
((AbstractApplicationContext) context).registerShutdownHook();
}
To every test
=> Closed Application Contexts after every test

training/src/test/java/com/revature/caliber/web/controller/implementations/TrainerControllerImplementationTest.java
Added static to method close() in TrainerControllerImplementationTest
=> Fixed non-working close() method

caliber/src/main/java/com/revature/caliber/controllers/AllController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainerBatchController.java, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/AssessmentServiceImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java, caliber/src/main/webapp/WEB-INF/applicationContext-security.xml, caliber/src/main/webapp/WEB-INF/beans.xml
=> Gatewayimpl

assessments/pom.xml, caliber/src/main/java/com/revature/caliber/gateway/impl/ApiGatewayImpl.java, caliber/src/main/java/com/revature/caliber/gateway/services/TrainingService.java, caliber/src/main/java/com/revature/caliber/gateway/services/impl/TrainingServiceImpl.java, caliber/src/main/webapp/WEB-INF/beans.xml, caliber/src/main/webapp/app/partials/home/vp-home.html, training/pom.xml, training/src/main/java/com/revature/caliber/training/data/Facade.java, training/src/main/java/com/revature/caliber/training/data/TraineeDAO.java, training/src/main/java/com/revature/caliber/training/data/implementations/FacadeImplementation.java, training/src/main/java/com/revature/caliber/training/data/implementations/TraineeDAOImplementation.java, training/src/main/java/com/revature/caliber/training/service/BusinessDelegate.java, training/src/main/java/com/revature/caliber/training/service/TraineeService.java, training/src/main/java/com/revature/caliber/training/service/implementations/BusinessDelegateImplementation.java, training/src/main/java/com/revature/caliber/training/service/implementations/TraineeServiceImplementation.java, training/src/main/java/com/revature/caliber/training/web/controllers/TraineeController.java
=> Controllers to angular

caliber/src/main/webapp/WEB-INF/applicationContext-security.xml, caliber/src/main/webapp/app/partials/assess/trainer-assess.html, caliber/src/main/webapp/app/resources/js/controllers/trainerAssessController.js
Creating of grades is now back. Gridded view for skill categories in assessments.
=> Creating of grades is now back. Gridded view for skill categories in assessments.

caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/java/com/revature/caliber/security/models/SalesforceUser.java
using trainer instead of trainerid in salesforceuser principal
=> updating security tactics

caliber/src/main/java/com/revature/caliber/beans/AssessmentType.java, caliber/src/main/java/com/revature/caliber/beans/NoteType.java, caliber/src/main/java/com/revature/caliber/beans/QCStatus.java, caliber/src/main/java/com/revature/caliber/beans/SkillType.java, caliber/src/main/java/com/revature/caliber/beans/TrainerRole.java, caliber/src/main/java/com/revature/caliber/beans/TrainingStatus.java, caliber/src/main/java/com/revature/caliber/beans/TrainingType.java
updated enums with JSON mappings
=> bean update

caliber/src/main/java/com/revature/caliber/controllers/ReportingController.java, caliber/src/main/java/com/revature/caliber/services/ReportingService.java
=> Merging Our Group CHanges into Sandbox

caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js, caliber/src/main/webapp/static/app/resources/js/factories/caliberDelegateFactory.js, caliber/src/main/webapp/static/app/resources/js/factories/trainerFactory.js
getAllAssessements to getAllAssessmentsForWeek
=> changed the name of the functions to make more sense

caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js
changed the hard coded week to $scope.currentWeek so the last week will load in initial page load in assess batch instead of week 1
=> took away the hard coded week for the inital load

caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js
Please prune after merge. Thank you sir
=> removed the thing breaking the page

caliber/src/main/webapp/static/app/partials/manage-batch.html
=> space added

caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java
trainee tier tostring comaprison to trainer role is changed to
getPrincipal(auth).getTier().equals(TrainerRole.TRAINER)
=> changed trainer tier to string check

caliber/src/main/webapp/static/app/partials/reports.html, caliber/src/main/webapp/static/app/resources/js/controllers/allReportController.js, caliber/src/main/webapp/static/app/resources/js/factories/chartFactories/lineChartFactory.js
Went through reports html line by line so hopefully I didn't erase anyone else's changes.
Functionality Status for Reports:
PDF is working but text is smudged and needs some formatting.
Charts and tables are working.
Batch Selector is working to select (but not NONE).
Week selector works but not deselecting. (i.e. when res-electing ALL)
Trainee Selector is working also works on deselect.
Year selector is there but is a WIP right now. Currently just decoration.
=> Uncharted sandbox 1

caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js
Submitting bug fix for Modals losing their scroll bar
Manage Batch page by selecting the view trainees
More updates may be required whenever multiple modals are created not referencing the currently updated two.
#495
=> now closing all modals and reopen underlying modal

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java
SOQL queries are done
#512 need this dependency
=> SOQL queries done

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java
fixing code smells to run Jenkins build
=> checking build health

caliber/src/main/webapp/static/app/resources/js/factories/allFactory.js
fixing sonarqube vulnerability
=> cleaning up vulnerability

caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js, caliber/src/main/webapp/static/app/resources/js/factories/chartsDelegateFactory.js, caliber/src/main/webapp/static/pages/index.html
=> last of sonarqube fixes

caliber/src/main/webapp/static/app/resources/js/factories/chartsDelegateFactory.js
=> sonarqube all clear!

caliber/src/main/webapp/static/app/resources/js/factories/chartsDelegateFactory.js
=> no more code smells

caliber/src/main/webapp/static/app/lib/css/angular-moment-picker.css
=> remove sonar scan in lib folder

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/salesforce/beans/SalesforceBatch.java, caliber/src/test/java/com/revature/caliber/Salesforce.java
=> location field for salesforce

caliber/src/main/java/com/revature/salesforce/beans/BatchTrainer.java
=> salesforce dao

caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/java/com/revature/caliber/security/impl/AuthorizationImpl.java, caliber/src/main/java/com/revature/caliber/security/impl/CacheControlFilter.java, caliber/src/main/webapp/WEB-INF/spring-security.xml, caliber/src/main/webapp/WEB-INF/web.xml, caliber/src/main/webapp/static/app/partials/abstracts/qc.html, caliber/src/main/webapp/static/app/partials/abstracts/trainer.html, caliber/src/main/webapp/static/app/partials/abstracts/vp.html, caliber/src/main/webapp/static/app/partials/reports/all.html, caliber/src/main/webapp/static/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/static/pages/index.html
=> boot controller refactor

caliber/src/main/webapp/static/app/resources/js/controllers/vpTrainerController.js
=> last code smell

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java
get less records from the salesforce. does not retrieve batches where a trainer has not been assigned
=> lighter salesforce query

caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/webapp/static/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/static/app/resources/js/factories/allFactory.js
=> renamed endpoints

caliber/src/main/webapp/static/app/partials/manage/import-batch-modal.html, caliber/src/main/webapp/static/app/partials/manage/view-trainees-modal.html
=> style modal.. just need to remove the little line

caliber/src/main/webapp/static/app/partials/manage/import-batch-modal.html
=> style modal

caliber/src/main/java/com/revature/caliber/validator/ValidBatch.java
=> turn on validation

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java, caliber/src/main/webapp/static/app/resources/js/controllers/qcAssessController.js
Address #558 by giving a temporary NoteId before waiting for the Promise to complete. This way, the user can click faces and notes very rapidly without worrying about duplicates
=> fix the noteId update delay

caliber/src/main/webapp/static/app/resources/js/controllers/allReportController.js
=> code smells

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java
show QC notes and trainer notes in proper places on Trainee Overall
#577
=> trainee overall showing proper notes

caliber/src/main/webapp/static/app/partials/category/manage-categories.html, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html
User can unassign a co-trainer from a batch. 
the one line I wrote
=> unassign co-trainer

caliber/src/main/webapp/static/app/resources/css/app.css, caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js, caliber/src/main/webapp/static/app/resources/js/factories/chartFactories/barChartFactory.js, caliber/src/main/webapp/static/app/resources/js/factories/chartFactories/doughnutChartFactory.js
=> bolder smileys and charts

caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js
Remove known datepicker bugs
If user fails date validation or updates existing batch date does not appear to change on modal
=> known datepicker bugs fixed!

caliber/src/main/webapp/static/app/partials/assess/qc-assess.html, caliber/src/main/webapp/static/app/partials/assess/trainer-assess.html, caliber/src/main/webapp/static/app/partials/manage/batch-axillary-modals.html, caliber/src/main/webapp/static/app/partials/manage/import-batch-modal.html, caliber/src/main/webapp/static/app/partials/reports.html, caliber/src/main/webapp/static/app/resources/css/app.css, caliber/src/main/webapp/static/app/resources/js/controllers/qcAssessController.js
=> more readable dropdowns

caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/resources/beans.xml, caliber/src/main/resources/log4j.properties, caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/WEB-INF/web.xml
=> preparing for go-live

caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/services/SalesforceService.java
=> debugging salesforce configuration #dev-prod-parity-yo

caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/java/com/revature/caliber/data/BatchDAO.java, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html, caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js
=> Not gracefully done, but done

caliber/src/main/java/com/revature/caliber/beans/Address.java, caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/java/com/revature/caliber/data/BatchDAO.java, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html, caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js, caliber/src/main/webapp/static/app/resources/js/factories/allFactory.js, caliber/src/main/webapp/static/app/resources/js/factories/caliberDelegateFactory.js
My push made a new branch while attempting to push
=> Quantum local ca

caliber/src/main/java/com/revature/caliber/beans/Batch.java, caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/main/java/com/revature/caliber/data/AddressDAO.java, caliber/src/main/java/com/revature/caliber/services/TrainingService.java, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html, caliber/src/test/java/com/revature/caliber/test/TrainingTest.java
Adding dropdown to dev branch
Caliber
no
611
no
=> Quantum ca

caliber/src/main/java/com/revature/caliber/controllers/TypeController.java
- To allow trainer access to list of assessment types.
- On line 118 of TypeController java class, the trainer role is added.
- This is a hotfix.
=> Allow trainer access to assessment types

caliber/src/test/java/com/revature/caliber/test/CategoryTest.java
Build failed so i edited the file which caused it to fail
on top of each function in the file i removed the @test annotation
=> removed the @Test annotation on not yet implmented test acses

caliber/src/test/resources/setup.sql
Added sequence for ADDRESS_ID_SEQUENCE: 
CREATE SEQUENCE ADDRESS_ID_SEQUENCE  MINVALUE 3080  INCREMENT BY 1 START WITH 3080;
To add sequence for ADDRESS_ID_SEQUENCE
Where the creation query for Address_Id_Sequence is.
=> Updated setup.sql

caliber/src/test/resources/setup.sql
Error in previous build because says sequence already exists - so edited script so if not exists
=> Added "if not exists" for address sequence

caliber/src/main/webapp/static/app/resources/js/controllers/qcHomeController.js, caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js, caliber/src/main/webapp/static/app/resources/js/controllers/vpHomeController.js
Hotfix issue 605 and 611
In trainerAssessController.js,
Line 532
In qcHomeController.js,
Line 388
In vpHomeController.js,
Line 399
=> hotfix 605 and 611

caliber/src/main/java/com/revature/caliber/controllers/EvaluationController.java, caliber/src/main/java/com/revature/caliber/controllers/TypeController.java, caliber/src/test/java/com/revature/caliber/test/integration/AssessmentTest.java, caliber/src/test/java/com/revature/caliber/test/integration/CategoryTest.java, caliber/src/test/java/com/revature/caliber/test/integration/EvaluationTest.java, caliber/src/test/java/com/revature/caliber/test/integration/PDFServiceTest.java, caliber/src/test/java/com/revature/caliber/test/integration/ReportingTest.java, caliber/src/test/java/com/revature/caliber/test/integration/TrainingTest.java, caliber/src/test/java/com/revature/caliber/test/unit/AssessmentDAOTest.java, caliber/src/test/java/com/revature/caliber/test/unit/BatchDAOTest.java
#663 Overall feedback not showing up on report
Changes were made to the EvaluationController.java and TypeController.java. Added Trainer to the authorized role annotations for the required get requests.
#663
=> Gave Trainer authorization to request qc notes and feedback

caliber/src/main/webapp/static/app/partials/assess/qc-assess.html
To fixed the year drop down not showing for a year with no data.
First line with changes.
#667
=> Fixed issue 667

caliber/src/main/java/com/revature/caliber/beans/Address.java, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html
pretty obvious change needed here..
=> address active field is now boolean instead of int

caliber/src/test/java/com/revature/caliber/test/uat/AddAssessmentFeature.java
=> cukes code smell

caliber/src/test/java/com/revature/caliber/test/unit/AddressDAOTest.java
=> Fixed updateAddress and findAddress stepping on each others' toes

caliber/src/main/java/com/revature/caliber/data/BatchDAO.java
Fix Phantom batch bug.
Only 1 method was changed, 3 lines of code in total.
See #551
#551
=> Fixed Phantom Batch issue

caliber/src/main/java/com/revature/caliber/services/ReportingService.java
One line change, off by one issue causing company average to miscalculate slightly (or in cases of one week old batches with only first week assessments to miscalculate significantly lower than it should be)
#677
=> fixed off by one error

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/webapp/static/app/partials/manage/import-batch-modal.html, caliber/src/main/webapp/static/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/static/app/resources/js/controllers/vpManageController.js, caliber/src/main/webapp/static/app/resources/js/factories/allFactory.js, caliber/src/test/java/com/revature/caliber/Salesforce.java
some UI changes to the import batch modal. there was an error in the $http call for the batch details (returned response instead of response.data in the factory)
#678
=> salesforce fix

caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/security/Authorization.java, caliber/src/main/java/com/revature/caliber/security/impl/AuthorizationImpl.java
=> salesforce exposed token issue

caliber/src/main/java/com/revature/caliber/security/Authorization.java
=> salesforce exposed token issue reset

caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java, caliber/src/test/java/com/revature/caliber/test/api/AbstractAPITest.java, caliber/src/test/java/com/revature/caliber/test/api/TrainerAPITest.java
AbstractAPITest refactored to create a base RequestSpecification to authenticate requests for API tests
=> abstract api testing

caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/java/com/revature/caliber/services/SalesforceService.java, caliber/src/main/java/com/revature/salesforce/beans/SalesforceTrainee.java, caliber/src/test/java/com/revature/caliber/test/api/AbstractAPITest.java
added new fields to marshalling process
=> salesforce to trainee bean

caliber/src/test/java/com/revature/caliber/test/api/TrainingAPITest.java
=> fix getAllTrainers test assertions

caliber/src/test/java/com/revature/caliber/test/api/TrainingAPITest.java
=> import missing

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java
=> notedao fix

caliber/src/main/java/com/revature/caliber/services/ReportingService.java
Fixing the issue where first name only trainers broke the app: #721 
ReportingService
First name of trainer
Who only has a first name
=> Fix for #721

caliber/src/main/java/com/revature/caliber/beans/Trainer.java, caliber/src/test/java/com/revature/caliber/test/unit/TrainerDAOTest.java
Resolved Trainer email not updating issue
Trainer.java (bean) and TrainerDAOTest.java
Refactored test for updating trainer email. Passes.
=> Resolved Trainer email not updating issue

caliber/src/main/java/com/revature/caliber/controllers/ReportingController.java, caliber/src/main/webapp/static/app/partials/home/qc-home.html, caliber/src/main/webapp/static/app/partials/home/vp-home.html
Fix issue #733 
ReportingController (L220), qc-home, vp-home
=> Fixed issue 733

caliber/src/main/webapp/static/app/partials/assess/trainer-assess.html, caliber/src/main/webapp/static/app/resources/js/controllers/trainerAssessController.js
Fixing of 0 grade input issue #544
issue/544
When a grade of 1 is used:
When a grade of 0 is used:
=> Fixing of 0 grade input issue #544

caliber/src/main/webapp/static/app/partials/home/qc-home.html, caliber/src/main/webapp/static/app/partials/home/vp-home.html
Locations updates change address table but not Batch Location Column #759
qc-home, vp-home
Add true arugment to enable strict filter on cities on vp-home and qc-home
=> Locations updates change address table but not Batch Location Column #759

caliber/src/main/java/com/revature/caliber/email/Mailer.java, caliber/src/main/java/com/revature/caliber/email/emailTemplate.html, caliber/src/main/java/com/revature/caliber/services/EmailService.java, caliber/src/main/webapp/static/app/partials/email/emailTemplate.html
Pushing my changes to the email template.
=> Issue736 Andrew- Email formatting changes

caliber/src/main/java/com/revature/caliber/controllers/TrainingController.java
issue/#763 QC Role cannot add week in Quality Audit page #763
TrainerController.java @ line~343
=> issue/#763 QC Role cannot add week in Quality Audit page #763

caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/resources/css/app.css, caliber/src/main/webapp/static/app/resources/js/controllers/panelModalController.js
=> fixed panel highlight color

caliber/src/main/java/com/revature/caliber/beans/PanelFeedback.java, caliber/src/main/java/com/revature/caliber/controllers/PanelController.java, caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/partials/panel/panelhome.html, caliber/src/main/webapp/static/app/resources/js/controllers/panelModalController.js
Various changes to the feedback from yesterday
To make it work on the dev server, you may need to remove the non-nullable constraint on the "panelist_comments" column in the "caliber_panel_feedback" table. Also to double check the message of someone's first panel and, as you'l hopefully notice, one less click!
=> Various bug fixes and validation

caliber/src/main/java/com/revature/caliber/beans/Panel.java, caliber/src/main/java/com/revature/caliber/controllers/PanelController.java, caliber/src/main/java/com/revature/caliber/validator/PanelValidator.java, caliber/src/main/java/com/revature/caliber/validator/ValidPanel.java, caliber/src/main/resources/spring-security.xml, caliber/src/test/java/com/revature/caliber/test/api/PanelAPITest.java
Everything I changed was in the createPanel() method in the PanelController class
=> Fixed API test and fixed overall panel status bug in case of someone sabotaging a trainee's panel(you know, just in case...)

caliber/src/test/java/com/revature/caliber/test/api/TrainingAPITest.java
=> added two batches to test data set

caliber/src/test/java/com/revature/caliber/test/integration/ReportingServiceTest.java
=> removed testing of unused method

caliber/src/main/java/com/revature/caliber/services/ReportingService.java, caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/resources/js/factories/chartFactories/lineChartFactory.js
=> Panel Y-Axis Max change and Another undefined value fix

caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/resources/js/config/routeConfig.js, caliber/src/main/webapp/static/app/resources/js/factories/authFactory.js
Fix routing so that user is sent to log in if they try to access a page without logging in.
routeConfig.js in the js/config folder
authFactory.js in the js/factories folder
The original issue asked for a solution in Spring Security but the errors were in the Client-Side code.
[ Page Bookmark Error #788 ] (https://github.com/revaturelabs/caliber/issues/788)
=> Team variables 788

caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/partials/panel/panelhome.html, caliber/src/main/webapp/static/app/partials/reports.html, caliber/src/main/webapp/static/app/resources/css/app.css, caliber/src/main/webapp/static/app/resources/js/controllers/allReportController.js, caliber/src/main/webapp/static/app/resources/js/controllers/panelModalController.js
Remove dropdown on Panels and Reports and load trainee list options on user input
Controllers:
allReportController.js
panelModalController.js
Partials:
reports.html
panelHome.html
CSS:
app.css
1) Wait for input before loading trainee list
2) Only display options if input characters are more than one (backspacing to blank field shows no options)
3) Hide dropdown arrow
Search Box Performance #796
=> Team variables 796

caliber/src/main/webapp/static/app/partials/panel/panelmodal.html, caliber/src/main/webapp/static/app/resources/js/controllers/panelModalController.js
=> corrected Create Panel form after team merge

caliber/src/main/java/com/revature/caliber/controllers/AssessmentController.java, caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/controllers/CategoryController.java, caliber/src/main/java/com/revature/caliber/controllers/EvaluationController.java, caliber/src/main/java/com/revature/caliber/controllers/PDFController.java, caliber/src/main/java/com/revature/caliber/controllers/PanelController.java, caliber/src/main/java/com/revature/caliber/controllers/ReportingController.java, caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/controllers/TypeController.java
Added cross origin annotations to controllers to allow the janus server.
Since the current app is being hosted by the api, they shouldn't need values added into the CrossOrigins
=> updated CORS for the controllers to allow janus

caliber/src/main/resources/schema-generator.sql
=> Fixed triggers with no forward slashes.

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java, caliber/src/main/java/com/revature/caliber/services/EvaluationService.java, caliber/src/main/resources/spring-security.xml
1. to add the method to the EvaluationService layer in the service package to call the method in the noteDAO layer in order to fetch all notes from the batch.
2. added the JUnit test for the method  "findAllQCTraineeNotesForAllWeeks" from the NoteDAO in NoteDAOTest
3. fixed the end of class spacing as convention in the evaluationService class
4. fixed the end of class spacing as convention in the noteDAO class 
noteDao.java in data package line number: 340
EvaluationService.java in package service, line number: 248
NoteDAOTest.java in package com.revature.caliber.test.unit
fixed the spacing issue as mentioned by Patrick. As commented on the last pull request, the issue was fixed by designing the hibernate query using join, now it does work on the local machine without any issues. 
no …
=> Team q cator dev

caliber/src/main/java/com/revature/caliber/data/NoteDAO.java, caliber/src/main/java/com/revature/caliber/services/EvaluationService.java, caliber/src/main/webapp/static/app/resources/js/controllers/qcAssessController.js, caliber/src/test/java/com/revature/caliber/test/integration/EvaluationServiceTest.java, caliber/src/test/java/com/revature/caliber/test/unit/NoteDAOTest.java
moved the auto-flag logic to the backend *where it belongs*
next commit should check if the trainee is flagged after updating the QC
=> flagging bits

caliber/src/main/java/com/revature/caliber/controllers/AssessmentController.java, caliber/src/main/java/com/revature/caliber/controllers/BootController.java, caliber/src/main/java/com/revature/caliber/controllers/CategoryController.java, caliber/src/main/java/com/revature/caliber/controllers/EvaluationController.java, caliber/src/main/java/com/revature/caliber/controllers/PDFController.java, caliber/src/main/java/com/revature/caliber/controllers/PanelController.java, caliber/src/main/java/com/revature/caliber/controllers/ReportingController.java, caliber/src/main/java/com/revature/caliber/controllers/SalesforceController.java, caliber/src/main/java/com/revature/caliber/controllers/TypeController.java
Added cross origin annotations to controllers to allow the janus server.
Since the current app is being hosted by the api, they shouldn't need values added into the CrossOrigins
=>  added cross origin annotations to controllers to allow access to janus

caliber/src/main/java/com/revature/caliber/services/ReportingService.java, caliber/src/main/webapp/static/app/partials/home/qc-home.html, caliber/src/main/webapp/static/app/partials/home/view-audit-modal.html, caliber/src/main/webapp/static/app/partials/home/vp-home.html, caliber/src/main/webapp/static/app/partials/qc-display.html, caliber/src/main/webapp/static/app/resources/js/controllers/qcHomeController.js, caliber/src/main/webapp/static/app/resources/js/controllers/vpHomeController.js, caliber/src/main/webapp/static/app/resources/js/factories/chartFactories/barChartFactory.js
- Fixed issue with overall batch status on VP home page and the QC home page not showing information from the correct batch.  Made to match the stacked graph's week.
- Fixed issue with clicking on the stacked graph creating a modal with the wrong week's trainee information.  Made to match the stacked graph's week.
- ReportingService.java
- vpHomeController.js
-- vp-home.html
- qcHomeController.js
-- qc-home.html
Altered methods involved were already tested in previous iterations.
[QC stacked bar graph not accurate #822](https://github.com/revaturelabs/caliber/issues/822)
None.
=> Team bug dev

caliber/src/test/java/com/revature/caliber/test/unit/BatchUpdateTest.java
=> salesforce sync

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> logging and monitoring

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> refactoring logging

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> transient object fix

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> transient trainer

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/java/com/revature/caliber/services/SalesforceService.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
Reverts revaturelabs/caliber#863
This functionality is not ready yet. We need to consider null trainers in Salesforce batch more closely
=> Revert "Development"

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java, caliber/src/main/resources/spring-security.xml
=> salesforce sync with past years batches

caliber/src/main/java/com/revature/caliber/beans/SkillType.java, caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/java/com/revature/caliber/services/SalesforceService.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java, caliber/src/main/java/com/revature/salesforce/beans/SalesforceBatch.java
=> null trainer fix, cotrainer salesforce sync, and skill type enums

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java, caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java, caliber/src/main/java/com/revature/caliber/validator/BatchValidator.java, caliber/src/main/resources/spring-security.xml, caliber/src/main/webapp/static/app/partials/manage/edit-batch-modal.html, caliber/src/main/webapp/static/app/resources/js/controllers/qcManageController.js, caliber/src/main/webapp/static/app/resources/js/controllers/trainerManageController.js
=> date picker and salesforce sync

caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> cotrainer problem

caliber/src/main/java/com/revature/caliber/data/TraineeDAO.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> I am now a human to August

caliber/src/main/java/com/revature/caliber/validator/BatchValidator.java
=> me and my null checks

caliber/src/main/java/com/revature/caliber/data/SalesforceDAO.java
=> hotfix for null trainer problem

caliber/src/main/java/com/revature/caliber/salesforce/SalesforceTransformerToCaliber.java
=> new salesforce skill types

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> batch update midnight

caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java
=> revpro sync

caliber/src/main/webapp/static/app/partials/manage/trainee-axillary-modals.html
Show trainer name when picking a batch to switch a trainee to
=> show trainer name on switch batch

caliber/src/main/java/com/revature/caliber/services/RevProBatchImportService.java, caliber/src/main/java/com/revature/caliber/tasks/BatchUpdate.java, caliber/src/main/resources/spring-security.xml
=> tryna get around nullpointer

caliber/src/test/java/com/revature/caliber/test/integration/EvaluationServiceTest.java, caliber/src/test/java/com/revature/caliber/test/unit/NoteDAOTest.java
=> revpro hotfix

caliber/src/main/java/com/revature/caliber/revpro/quiz/models/QuizResult.java
=> export grades json

caliber/src/main/java/com/revature/caliber/tasks/FlagEmailTask.java
=> flag email sunday midnight

caliber/src/main/java/com/revature/caliber/beans/Trainee.java, caliber/src/main/java/com/revature/caliber/revpro/RevProCaliberTransformer.java, caliber/src/main/java/com/revature/caliber/revpro/beans/RevProTrainee.java, caliber/src/main/java/com/revature/caliber/revpro/beans/ScreeningInformation.java, caliber/src/main/resources/schema-generator.sql, scripts/version1.7-screen-score.sql
=> import fix
